[workspace]
name = "art-of-viz"
authors = ["deepthought <deepthough@postech.ac.kr>"]
channels = ["conda-forge"]
platforms = ["linux-64"]
version = "0.1.0"

[dependencies]
r-base = ">=4.3"
r-tidyverse = ">=2.0.0,<3"
r-ggplot2 = ">=4.0.2,<5"
r-ggtext = ">=0.1.2,<0.2"
r-showtext = ">=0.9_7,<0.10"
r-sysfonts = ">=0.8.9,<0.9"
r-metbrewer = ">=0.2.0,<0.3"
r-maps = ">=3.4.3,<4"
r-cowplot = ">=1.2.0,<2"
r-paletteer = ">=1.7.0,<2"
r-naniar = ">=1.1.0,<2"
r-patchwork = ">=1.3.2,<2"
r-glue = ">=1.8.0,<2"
r-scales = ">=1.4.0,<2"
r-knitr = ">=1.51,<2"
r-rmarkdown = ">=2.30,<3"
r-visdat = ">=0.6.0,<0.7"
r-sf = ">=1.0_24,<2"
r-devtools = ">=2.4.6,<3"
r-remotes = ">=2.5.0,<3"
r-pak = ">=0.9.2,<0.10"
quarto = ">=1.8.27,<2"
r-magick = ">=2.9.0,<3"
r-rsvg = ">=2.6.1,<3"
r-gifski = ">=1.32.0_2,<2"
r-gghighlight = ">=0.5.0,<0.6"
r-funspotr = ">=0.0.5,<0.0.6"
r-rcartocolor = ">=2.1.2,<3"
r-kableextra = ">=1.4.0,<2"
r-pander = ">=0.6.6,<0.7"
r-cropcircles = ">=0.2.4,<0.3"
r-ggimage = ">=0.3.5,<0.4"
r-geofacet = ">=0.2.4,<0.3"
r-ggally = ">=2.4.0,<3"
r-marquee = ">=1.2.1,<2"
r-openxlsx = ">=4.2.8.1,<5"
r-waffle = ">=1.0.2,<2"
r-imager = ">=1.0.8,<2"
r-reactable = ">=0.4.5,<0.5"
r-ggpattern = ">=1.2.1,<2"
r-ggforce = ">=0.5.0,<0.6"
r-colorspace = ">=2.1_2,<3"

[tasks]
install-r-pkgs = "R -e \"remotes::install_github('coolbutuseless/poissoned'); remotes::install_github('clauswilke/colorblindr'); install.packages(c('camcorder', 'tidytuesdayR'), repos='http://cran.r-project.org')\""
render = "quarto render"
